common: &common
  adapter: postgresql
  encoding: utf8
  pool: 20
  
development:
  <<: *common
  database: ubergo_development

production:
  <<: *common
  database: ubergo_development

test:
  <<: *common
  database: ubergo_test
